/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009-2016
 * All rights reserved.
 *
 * $Revision$
 * $Date$
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include "rtk_rtl8371c_table_struct.h"
#include "rtk_rtl8371c_tableField_list.h"

rtksw_table_t rtk_rtl8371c_table_list[] =
{

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "VLAN_TBL",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     3,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   RTL8371C_VLAN_TBLFIELD_LIST_END,
        /* table fields */          RTL8371C_VLAN_TBL_FIELDS
    },

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_IPMC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  5,
        /* total field numbers */   RTL8371C_L2_IPMCFIELD_LIST_END,
        /* table fields */          RTL8371C_L2_IPMC_FIELDS
    },

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_MC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  5,
        /* total field numbers */   RTL8371C_L2_MCFIELD_LIST_END,
        /* table fields */          RTL8371C_L2_MC_FIELDS
    },

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "L2_UC",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  5,
        /* total field numbers */   RTL8371C_L2_UCFIELD_LIST_END,
        /* table fields */          RTL8371C_L2_UC_FIELDS
    },

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ACL_ACT_ENTRY",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     2,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   RTL8371C_ACL_ACT_ENTRYFIELD_LIST_END,
        /* table fields */          RTL8371C_ACL_ACT_ENTRY_FIELDS
    },

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ACL_RULE_DATA",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  10,
        /* total field numbers */   RTL8371C_ACL_RULE_DATAFIELD_LIST_END,
        /* table fields */          RTL8371C_ACL_RULE_DATA_FIELDS
    },

    {
        #if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
        /* table name       */      "ACL_RULE_MASK",
        #endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */
        /* access table type */     1,
        /* table size */            64,
        /* total data registers */  9,
        /* total field numbers */   RTL8371C_ACL_RULE_MASKFIELD_LIST_END,
        /* table fields */          RTL8371C_ACL_RULE_MASK_FIELDS
    },
};

